# Generated by Django 3.0.6 on 2020-06-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='size',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(),
        ),
    ]
