# Generated by Django 3.0.7 on 2020-06-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20200610_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], default='Rent', max_length=5),
        ),
    ]
